cargo-features = ["publish-lockfile"]

[package]
name = "bootloader"
version = "0.4.0"
authors = ["Philipp Oppermann <dev@phil-opp.com>"]
license = "MIT/Apache-2.0"
description = "An experimental pure-Rust x86 bootloader."
repository = "https://github.com/rust-osdev/bootloader"
publish-lockfile = true
edition = "2018"

[dependencies]
xmas-elf = "0.6.2"
x86_64 = "0.3.5"
usize_conversions = "0.2.0"
fixedvec = "0.2.3"
apic = { git = "https://github.com/rcore-os/apic-rs" }

[dependencies.font8x8]
version = "0.2.4"
default-features = false
features = ["unicode"]

[features]
default = ["recursive_page_table"]
vga_320x200 = []
recursive_page_table = []
map_physical_memory = []

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = false
debug = true

[package.metadata.docs.rs]
features = [ "recursive_page_table", "map_physical_memory" ]
