[package]
name = "builder"
version = "0.1.0"
authors = ["Philipp Oppermann <dev@phil-opp.com>"]
edition = "2018"

[dependencies]
xmas-elf = "0.6.2"
byteorder = "1.2.7"
args = "2.2.0"
getopts = "0.2.18"
